spring:
  datasource:
    url: jdbc:mysql://mysql-de:3306/dataease?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password123@mysql
